version: '3'
services:
    payara-full:
        build: mypayara-full
        environment:
           - ADMIN_PASSWORD=admin
        ports:
            - "8080:8080"
            - "4848:4848"
        depends_on:
            - db

    db:
        image: oscarfonts/h2:2.1.210
        ports:
            - "1521:1521"
            - "8081:81"
        environment:
            H2_OPTIONS: '-ifNotExists'
        volumes:
            - h2-data:/opt/h2-data
volumes:
  h2-data:              
