version: '3.7'

services:

    payara-full:
        build: mypayara-full
        ports:
            - "8080:8080"
            - "4848:4848"
        depends_on:
            - db
    db:
        image: postgres:16
        environment:
            POSTGRES_USER: dba
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: payaradb
        ports:
            - "5432:5432"
        volumes:
            - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
