version: '2'
services:
    payara-full:
        build: mypayara-full
        environment:
           - ADMIN_PASSWORD=admin
        ports:
            - "8080:8080"
            - "4848:4848"
        volumes:
          # application to deploy at startup
            - "./data/payara/deployments:/opt/payara/deployments"
         ### BEST TO BUILD A CUSTOM IMAGE WITH 
         # COPY myapplication.war $DEPLOY_DIR
            
        depends_on:
            - db

    db:
        image: oscarfonts/h2:1.4.199
        ports:
            - "1521:1521"
            - "8081:81"
        environment:
            H2_OPTIONS: '-ifNotExists'
        volumes:
            - ./data/h2data:/opt/h2-data
